// Generated by ts-to-zod
import { z } from 'zod'

export const geoSchema = z.object({
  lat: z.string().optional(),
  lng: z.string().optional(),
})

export const companySchema = z.object({
  name: z.string().optional(),
  catchPhrase: z.string().optional(),
  bs: z.string().optional(),
})

export const addressSchema = z.object({
  street: z.string().optional(),
  suite: z.string().optional(),
  city: z.string().optional(),
  zipcode: z.string().optional(),
  geo: geoSchema,
})

export const userSchema = z.object({
  id: z.number().optional(),
  name: z.string(),
  username: z.string().optional(),
  email: z.string(),
  address: addressSchema.optional(),
  phone: z.string().optional(),
  website: z.string().optional(),
  company: companySchema.optional(),
})

export const dbSchema = z.object({
  users: z.array(userSchema),
})
